### ISSUE TITLE
Failed job with multiple firewatch tickets does not create the tickets in chronological order.

### ISSUE THREAD

**Issue by ascerra** [RedHatQE/firewatch#104]
When we have a job that fails in multiple steps and leads to the creation of multiple firewatch tickets, the tickets do not get created in the order that the failed steps were run.

For example consider these 3 tickets created from a single failed ACM run
[LPINTEROP-3777](https://issues.redhat.com/browse/LPINTEROP-3777)
[LPINTEROP-3778](https://issues.redhat.com/browse/LPINTEROP-3778)
[LPINTEROP-3779](https://issues.redhat.com/browse/LPINTEROP-3779)

Mapping the step captured within the ticket and the order of the failed steps that were run the tickets look like this
[LPINTEROP-3779](https://issues.redhat.com/browse/LPINTEROP-3779)
[LPINTEROP-3777](https://issues.redhat.com/browse/LPINTEROP-3777)
[LPINTEROP-3778](https://issues.redhat.com/browse/LPINTEROP-3778)
*Meaning that 3779's failure actually occurred before 3777 and 3778 but since the numbers aren't in order when a watcher goes to debug this they might make an incorrect assumption about the order the steps were run.

If we could make the firewatch tickets in order of the steps that failed that would help watchers understand these situations a bit easier.

Side note:
This particular scenario is [being improved here to prevent cascading failures](https://github.com/openshift/release/pull/45389/files#r1399340157), but we could see this type of example in other scenarios as well.

**Comment by calebevans** [comment]
I can look into this, but I don't know that there is a way for me to accurately determine the order of steps. If it is not a value provided in Prow/OCPCI, I don't know that it is worth trying to determine that.

@ascerra
