### ISSUE TITLE
JIRA 401 Error raised when adding passed job notification

### ISSUE THREAD

**Issue by amp-rh** [RedHatQE/firewatch#188]
See [this build log](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-jboss-fuse-fuse-xpaas-qe-container-main-jboss-fuse-ocp4.16-lp-interop-jboss-fuse-interop-aws/1787362797902893056#1:build-log.txt%3A68).

This is the only instance observed at this time, but I will update here if I find others.

**Comment by calebevans** [comment]
Similar to https://github.com/RedHatQE/qe-metrics/issues/125

Will fix this along with that issue.
