### ISSUE TITLE
[INTEROP-7490] Add link to job history to bug descriptions - 226

### ISSUE THREAD

**Issue by msi-b1** [RedHatQE/firewatch#227]
[Auto generated]
Number: [#226]

**Comment by redhat-qe-bot2** [comment]
[38;5;29mfirewatch[0m[pull_request][76d2-11ef-9717-25e90d3506dd][PR 226]: Closing issue for PR: [INTEROP-7490] Add link to job history to bug descriptions.
PR was closed.
